name: list_firebase
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  intl: ^0.20.2 
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  flutter_local_notifications: ^19.4.0
  flutter_slidable: ^4.0.0
  timezone: ^0.10.1
  uuid: ^4.5.1
  mocktail: ^1.0.4
  fake_cloud_firestore: ^4.0.0
  firebase_core_platform_interface: ^6.0.0
  firebase_auth_mocks: ^0.15.0
  mockito: ^5.5.1
  build_runner: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.6
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/splash_logo/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Bold.ttf

flutter_native_splash:
  color: "#121212"
  color_dark: "#121212"
  image: assets/splash_logo/logo.png
  android: true
  ios: true
  fullscreen: true
  android_gravity: center
  ios_content_mode: center
